# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Natt/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-6204-DESKTOP-BUGDRN4/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.cache/wt [current_project]
set_property parent.project_path C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/Sources/ALU.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/new/ALU_display_controller.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/Sources/BCD_to_7seg.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/Sources/Binary_to_BCD.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/Sources/TDM.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/new/UART_RX_CTRL_MOD.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/Sources/clock_divider.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/Sources/digit_selector.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/Sources/nbit_counter.sv
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/new/UART_calc_top.sv
}
read_verilog -library xil_defaultlib {
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/uart/data_sync.v
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/uart/uart_basic.v
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/uart/uart_baud_tick_gen.v
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/uart/uart_rx.v
  C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/sources_1/imports/uart/uart_tx.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/constrs_1/imports/constrs/UART_master_const.xdc
set_property used_in_implementation false [get_files C:/Users/Natt/Documents/GitHub/ELO212/project_7.3.3.3_ver_2_electric_boogaloo/project_7.3.3.3_ver_2_electric_boogaloo.srcs/constrs_1/imports/constrs/UART_master_const.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top UART_calc_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef UART_calc_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file UART_calc_top_utilization_synth.rpt -pb UART_calc_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
