webtalk_init -webtalk_dir C:/Users/na-tt/Documents/ELO212/project_6_extended.2.2/project_6_extended.2.2.sim/sim_1/behav/xsim/xsim.dir/double_dabble_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jul 27 17:54:16 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7e0b1352-1725-4f38-8528-c9b79b0cb6e1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "27a62b62406343f583e99c80cbf4555c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6656_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3117664283 -regid "" -xml C:/Users/na-tt/Documents/ELO212/project_6_extended.2.2/project_6_extended.2.2.sim/sim_1/behav/xsim/xsim.dir/double_dabble_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/na-tt/Documents/ELO212/project_6_extended.2.2/project_6_extended.2.2.sim/sim_1/behav/xsim/xsim.dir/double_dabble_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/na-tt/Documents/ELO212/project_6_extended.2.2/project_6_extended.2.2.sim/sim_1/behav/xsim/xsim.dir/double_dabble_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
